FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY infra/server.sh infra/server.sh
RUN chmod +x infra/server.sh
CMD ["bash", "infra/server.sh"]
