FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

RUN mkdir -p /app/mlflow_local/artifacts

EXPOSE 5000

CMD ["mlflow", "server", \
     "--backend-store-uri", "sqlite:////app/mlflow_local/mlflow.db", \
     "--default-artifact-root", "/app/mlflow_local/artifacts", \
     "--host", "0.0.0.0", "--port", "5000"]
